"""add_debate_platform_tables

Revision ID: db2017486dcd
Revises: 8a68607150e0
Create Date: 2026-04-15 21:29:42.197499

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db2017486dcd'
down_revision: Union[str, None] = '8a68607150e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_debate_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('debates',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('agent_prompt', sa.Text(), nullable=False),
    sa.Column('agent_voice_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('livekit_room_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('livekit_room_name')
    )
    op.create_index(op.f('ix_debates_user_id'), 'debates', ['user_id'], unique=False)
    op.create_table('debate_analyses',
    sa.Column('debate_id', sa.Uuid(), nullable=False),
    sa.Column('argument_strength', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logical_fallacies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persuasiveness', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_moments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=False),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_analyses_debate_id'), 'debate_analyses', ['debate_id'], unique=True)
    op.create_table('debate_embeddings',
    sa.Column('debate_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('speaker', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_embeddings_debate_id'), 'debate_embeddings', ['debate_id'], unique=False)
    op.create_index('ix_debate_embeddings_embedding_hnsw', 'debate_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_debate_embeddings_user_id'), 'debate_embeddings', ['user_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('debate_id', sa.Uuid(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('speaker_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_debate_id'), 'transcripts', ['debate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_debate_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_debate_embeddings_user_id'), table_name='debate_embeddings')
    op.drop_index('ix_debate_embeddings_embedding_hnsw', table_name='debate_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_debate_embeddings_debate_id'), table_name='debate_embeddings')
    op.drop_table('debate_embeddings')
    op.drop_index(op.f('ix_debate_analyses_debate_id'), table_name='debate_analyses')
    op.drop_table('debate_analyses')
    op.drop_index(op.f('ix_debates_user_id'), table_name='debates')
    op.drop_table('debates')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
